apps/tareas/urls.py
from django.urls import path
from apps.tareas.views import *
from django.contrib.auth.decorators import login_required

app_name = 'tareas'

urlpatterns = [
    path('tareas/', login_required(TareasListView.as_view()), name='tareas_listar'),
    path('tareas/crear/', login_required(TareaCreateView.as_view()), name='tareas_crear'),
    path('editar/<int:pk>/', login_required(TareaUpdateView.as_view()), name='tareas_editar'),
    path('ver/<int:pk>/', login_required(TareaTerminarView.as_view()), name='tareas_ver'),
    path('eliminar/<int:pk>/', login_required(TareaDeleteView.as_view()), name='tareas_eliminar'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.login.urls')),
    path('', include('apps.tareas.urls')),
]

templates/base/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %} {% endblock %}</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
        integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css">

</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="{% url 'tareas:tareas_listar' %}"><i class="fa-solid fa-diagram-project"></i> GTareas</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
            aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            {% if user.is_authenticated %}
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                      <a href="{% url 'logout' %}" class="btn btn-danger"><i class="fa-solid fa-power-off"></i> Salir</a>
                </li>
            </ul>
            {% else %}
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                      <a href="{% url 'login' %}" class="btn btn-primary"><i class="fa-solid fa-right-to-bracket"></i> Ingresar</a>
                </li>
            </ul>
            {% endif %}
        </div>
    </nav>

    <div class="container mt-5">
        <div class="card">
            <div class="card-header">
                {% block content-title %}
                {% endblock %}
            </div>
            <div class="card-body">
                {% block content %}
                {% endblock %}
            </div>
            <div class="card-footer">
                <div class="text-center">MiniTaskSys</div>
            </div>
        </div>
    </div>
    
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous">
    </script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
        integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous">
    </script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js"
        integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous">
    </script>

    {% block js %}

    {% endblock %}

    {% block css %}
    
    {% endblock %}
</body>

</html>