apps/tareas/urls.py
from django.urls import path
from apps.tareas.views import *
from django.contrib.auth.decorators import login_required

app_name = 'tareas'

urlpatterns = [
    path('tareas/', login_required(TareasListView.as_view()), name='tareas_listar'),
    path('tareas/crear/', login_required(TareaCreateView.as_view()), name='tareas_crear'),
    path('editar/<int:pk>/', login_required(TareaUpdateView.as_view()), name='tareas_editar'),
    path('ver/<int:pk>/', login_required(TareaTerminarView.as_view()), name='tareas_ver'),
    path('eliminar/<int:pk>/', login_required(TareaDeleteView.as_view()), name='tareas_eliminar'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.login.urls')),
    path('', include('apps.tareas.urls')),
]

apps/tareas/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import MinValueValidator
from datetime import date
from django.core.validators import RegexValidator

# Create your models here.

alphanumeric = RegexValidator(r'^[0-9a-zA-Z ,.;¿?¡!]*$', 'Se aceptan solamente valores alfanuméricos con coma (,) y punto (.).')

# Prioridades
class Prioridad(models.Model):
    nombre = models.TextField(verbose_name='Nombre', unique=True, validators=[alphanumeric])
    
    def __str__(self):
        return self.nombre

    class Meta:
        db_table = 'prioridades'
        verbose_name = 'Prioridad'
        verbose_name_plural = 'Prioridades'
        ordering = ['nombre']

# Tareas
class Tarea(models.Model):
    nombre = models.TextField(verbose_name='Nombre', validators=[alphanumeric])
    descripcion = models.TextField(verbose_name='Descripcion', validators=[alphanumeric])
    fecha_limite = models.DateField(validators=[MinValueValidator(limit_value=date.today)], verbose_name='Fecha Límite')
    terminada = models.BooleanField(default=False, verbose_name='Terminada')
    prioridad = models.ForeignKey(Prioridad, on_delete=models.CASCADE, verbose_name='Prioridad')
    usuario = models.ForeignKey(User, on_delete=models.DO_NOTHING, verbose_name='Usuario')

    def __str__(self):
        return self.nombre + " " + self.descripcion + " - Fecha Límite: " + " " + " - Terminada: " + " "

    class Meta:
        verbose_name = 'Tarea'
        verbose_name_plural = 'Tareas'
        db_table = 'tareas'
        ordering = ['terminada', '-fecha_limite']

apps/tareas/forms.py
from cProfile import label
from tkinter import Widget
from tokenize import Number
from django.forms import *
from .models import *  
from django import forms
from django.utils import timezone
from datetime import date

class TareaForm(ModelForm):
    class Meta:
        model = Tarea
        fields = ['nombre', 'descripcion', 'fecha_limite', 'prioridad']
        exclude = ['usuario']

        error_messages = {
            'nombre': {
                'required': 'El campo Nombre es requerido.',
            },
            'descripcion': {
                'required': 'El campo Descripción es requerido.',
            },
            'fecha_limite': {
                'required': 'El campo Fecha Límite es requerido.',
            },
            'prioridad': {
                'required': 'El campo Prioridad es requerido.',
                'invalid_choice': 'Seleccionar una opción válida.'
            },
        }

        labels = {
            'nombre': 'Nombre',
            'descripcion': 'Descripción',
            'fecha_limite': 'Fecha Límite',
            'prioridad': 'Prioridad'
        }
        widgets = {
            'nombre': TextInput(
                attrs={
                    'class': 'form-control'
                }
            ),

            'descripcion': Textarea(
                attrs={
                    'class': 'form-control'
                }
            ),

            'fecha_limite': DateInput(
                attrs={
                    'class': 'form-control',
                    'type': 'date',
                }
            ),

            'prioridad': Select(
                attrs={
                    'class': 'custom-select',
                }
            )

        }
    
    def clean_nombre(self):
        nombre = self.cleaned_data.get('nombre')
        if ((len(nombre) < 5) or (len(nombre) > 100)):
            raise forms.ValidationError('El Nombre debe tener entre 5 y 100 caracteres.')
        return nombre

    def clean_descripcion(self):
        descripcion = self.cleaned_data.get('descripcion')
        if ((len(descripcion) < 5) or (len(descripcion) > 100)):
            raise forms.ValidationError('La Descripción debe tener al menos 5 caracteres.')
        return descripcion

    def clean_fecha_limite(self):
        fecha_limite = self.cleaned_data.get('fecha_limite')
        formato_esperado = '%Y-%m-%d'
        fecha_actual = timezone.localdate()

        fecha_limite_str = fecha_limite.strftime(formato_esperado)
        if fecha_limite_str != self.data['fecha_limite']:
            raise forms.ValidationError('El formato de fecha es incorrecto.')

        if fecha_limite < fecha_actual:
            raise forms.ValidationError('La Fecha Límite debe ser mayor a la fecha actual.')
        return fecha_limite

apps/tareas/views.py
from audioop import reverse
from .models import *
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from .forms import *
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.shortcuts import redirect
from datetime import datetime, timedelta
from django.contrib.messages.views import SuccessMessageMixin

# Create your views here.

class TareasListView(ListView):
    model = Tarea
    template_name = 'listar.html'
    ordering = ['terminada', '-fecha_limite']

    def get_queryset(self):
        queryset = super().get_queryset()
        user = self.request.user
        start_date = self.request.GET.get('start_date')
        end_date = self.request.GET.get('end_date')
        
        if start_date:
            start_date = datetime.strptime(start_date, '%Y-%m-%d').date()
            queryset = queryset.filter(fecha_limite__gte=start_date)
        
        if end_date:
            end_date = datetime.strptime(end_date, '%Y-%m-%d').date()
            queryset = queryset.filter(fecha_limite__lte=end_date)
        
        queryset = queryset.filter(usuario=user)
        
        return queryset
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Listado de Tareas'
        context['start_date'] = self.request.GET.get('start_date')
        context['end_date'] = self.request.GET.get('end_date')
        return context

class TareaCreateView(SuccessMessageMixin, CreateView):
    model = Tarea
    form_class = TareaForm
    template_name = 'formulario.html'
    success_url = reverse_lazy('tareas:tareas_listar')
    success_message = 'Tarea Creada'

    def form_valid(self, form):
        form.instance.usuario = self.request.user
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Crear Tarea'
        return context

class TareaUpdateView(SuccessMessageMixin, UserPassesTestMixin, UpdateView):
    model = Tarea
    form_class = TareaForm
    template_name = 'formulario.html'
    success_url = reverse_lazy('tareas:tareas_listar')
    success_message = 'Tarea Modificada'

    def test_func(self):
        tarea = self.get_object()
        return tarea.usuario == self.request.user

    def handle_no_permission(self):
        return redirect('tareas:tareas_listar')

    def form_valid(self, form):
        form.instance.usuario = self.request.user
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Editar Tarea'
        return context

class TareaDeleteView(SuccessMessageMixin, UserPassesTestMixin, DeleteView):
    model = Tarea
    template_name = 'eliminar.html'
    success_url = reverse_lazy('tareas:tareas_listar')
    success_message = 'Tarea Eliminada'

    def test_func(self):
        tarea = self.get_object()
        return tarea.usuario == self.request.user

    def handle_no_permission(self):
        return redirect('tareas:tareas_listar')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Eliminar Tarea'
        return context

class TareaTerminarView(SuccessMessageMixin, UserPassesTestMixin, UpdateView):
    model = Tarea
    template_name = 'ver.html'
    fields = []
    success_url = reverse_lazy('tareas:tareas_listar')
    success_message = 'Tarea Terminada'

    def test_func(self):
        tarea = self.get_object()
        return tarea.usuario == self.request.user

    def handle_no_permission(self):
        return redirect('tareas:tareas_listar')

    def form_valid(self, form):
        tarea = form.save(commit=False)
        tarea.terminada = True
        tarea.save()
        return super().form_valid(form)

apps/tareas/templates/crear.html
{% extends "base/base.html" %}
{% block title %} Gestión de Tareas - {{ title }} {% endblock %}
{% block body %}

<div class="card">
    <div class="card-header">
      Mini-TaskSys
    </div>
    <div class="card-body">
      <h5 class="card-title">{{ title }}</h5>
    <form method="post">
        {% csrf_token %}

        {% if form.errors %}
        <div class="alert alert-danger alert-dismissible">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
            <h5><i class="icon fas fa-ban"></i> Ha ocurrido un error:</h5>
            <p class="text-danger">{{ form.errors }}</p>
        </div>
        {% endif %}
        <div class="form-group">
            <label> {{ form.nombre.label }} </label>
            {{ form.nombre }}
        </div>

        <div class="form-group">
            <label> {{ form.descripcion.label }} </label>
            {{ form.descripcion }}
        </div>

        <div class="form-group">
            <label> {{ form.fecha_limite.label }} </label>
            {{ form.fecha_limite }}
        </div>

        <div class="form-group">
            <label> {{ form.prioridad.label }} </label>
            {{ form.prioridad }}
        </div>

        <div class="form-group">
            <label> {{ form.usuario.label }} </label>
            {{ form.usuario }}
        </div>

        <button type="submit" class="btn btn-primary mt-2">Guardar</button>
    </form>
    </div>
    </div>
    
{% endblock %}

apps/tareas/templates/eliminar.html
{% extends "base/base.html" %}
{% block content-title %} Gestión de Tareas - {{ title }} {% endblock %}

{% block content %}
    <form method="post">
        {% csrf_token %}
        <h2>Seguro Eliminar?</h2>
        <div class="text-center">
            <button type="submit" class="btn btn-danger">Eliminar</button>
            <a href="{% url 'tareas:tareas_listar' %}" class="btn btn-secondary">Cancelar</a>
        </div>

    </form>
{% endblock %}

apps/tareas/templates/form.html
{% extends "base/base.html" %}
{% block title %} Gestión de Tareas - {{ title }} {% endblock %}
{% block body %}

<div class="card">
    <div class="card-header">
      Mini-TaskSys
    </div>
    <div class="card-body">
      <h5 class="card-title">{{ title }}</h5>
    <form method="post">
        {% csrf_token %}
        <div class="form-group">
            <label> {{ form.nombre.label }} </label>
            {{ form.nombre }}
        </div>

        <div class="form-group">
            <label> {{ form.descripcion.label }} </label>
            {{ form.descripcion }}
        </div>

        <div class="form-group">
            <label> {{ form.fecha_limite.label }} </label>
            {{ form.fecha_limite }}
        </div>

        <div class="form-group">
            <label> {{ form.prioridad.label }} </label>
            {{ form.prioridad }}
        </div>

        <div class="form-group">
            <label> {{ form.usuario.label }} </label>
            {{ form.usuario }}
        </div>

        <button type="submit" class="btn btn-primary mt-2">Guardar</button>
    </form>
    </div>
    </div>
    
{% endblock %}

apps/tareas/templates/formulario.html
{% extends "base/base.html" %}
{% block content-title %} Gestión de Tareas - {{ title }} {% endblock %}

{% block content %}
    <form method="post">
        {% csrf_token %}

        {% for field in form.visible_fields %}
            <div class="form-group">
                <label for="id_{{ field.name }}">{{ field.label }}:</label>
                {{ field }}

                {% if field.errors %}
                    <small>
                        {% for error in field.errors %}
                            <p class="text text-danger">{{ error|escape }}</p>
                        {% endfor %}
                    </small>
                {% endif %}

            </div>
        {% endfor %}
        <div class="text-center">
            <button type="submit" class="btn btn-primary">Guardar</button>
            <a href="{% url 'tareas:tareas_listar' %}" class="btn btn-secondary">Cancelar</a>
        </div>

    </form>
{% endblock %}

apps/tareas/templates/list.html
{% extends "base/base.html" %}
{% block title %} Gestión de Tareas - {{ title }} {% endblock %}
{% block body %}

<div class="card">
    <div class="card-header">
      Mini-TaskSys
    </div>
    <div class="card-body">
      <h5 class="card-title">Mis Tareas</h5>
      
      <table id="tproyectos" class="table table-bordered table-hover border-dark">
        <thead class="thead-dark">
            <tr>
                <th scope="col">Nombre</th>
                <th scope="col">Fecha Lím.</th>
                <th scope="col">Prioridad</th>
                <th scope="col">Acciones</th>
            </tr>
        </thead>
        <tbody>
            {% for t in object_list %}
            <tr>
                <td>{{ t.nombre }}</td> 
                <td>{{ t.fecha_limite }}</td>
                <td>{{ t.prioridad.nombre }} </td>
                <td>
                    <button type="button" class="btn btn-primary btn-sm"><i class="fa-solid fa-eye"></i></button>
                    <a href="#" class="btn btn-warning btn-sm"><i class="fa-solid fa-pen-to-square"></i></a>
                    <a href="#" class="btn btn-danger btn-sm"><i class="fa-solid fa-trash"></i></a>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    <a class="btn btn-success" href="{% url 'tareas:tareas_crear' %}" role="button">Nueva Tarea</a>
    </div>
</div>


    
{% endblock %}

{% block js %}
    <script src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js"></script>

    <script>
        $(document).ready(function() {
            $('#tproyectos').DataTable();
        } );
    </script>
{% endblock %}

{% block css %}
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.20/css/jquery.dataTables.min.css">
{% endblock %}

apps/tareas/templates/lista.html
{% extends "base/base.html" %}
{% block title %} Gestión de Tareas - {{ title }} {% endblock %}
{% block body %}

<div class="card">
    <div class="card-header">
      Mini-TaskSys
    </div>
    <div class="card-body">
      <h5 class="card-title">Mis Tareas</h5>
      
      <table id="tproyectos" class="table table-bordered table-hover border-dark">
        <thead class="thead-dark">
            <tr>
                <th scope="col">Nombre</th>
                <th scope="col">Fecha Lím.</th>
                <th scope="col">Prioridad</th>
                <th scope="col">Acciones</th>
            </tr>
        </thead>
        <tbody>
            {% for t in object_list %}
            <tr>
                <td>{{ t.nombre }}</td> 
                <td>{{ t.fecha_limite }}</td>
                <td>{{ t.prioridad.nombre }} </td>
                <td>
                    <a href="{% url 'tareas:tareas_terminar' t.id %}" class="btn btn-primary btn-sm"><i class="fa-solid fa-eye"></i></a>
                    <a href="{% url 'tareas:tareas_editar' t.id %}" class="btn btn-warning btn-sm"><i class="fa-solid fa-pen-to-square"></i></a>
                    <a href="{% url 'tareas:tareas_eliminar' t.id %}" class="btn btn-danger btn-sm"><i class="fa-solid fa-trash"></i></a>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    <a class="btn btn-success" href="{% url 'tareas:tareas_crear' %}" role="button">Nueva Tarea</a>
    </div>
</div>


    
{% endblock %}

{% block js %}
    <script src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js"></script>

    <script>
        $(document).ready(function() {
            $('#tproyectos').DataTable();
        } );
    </script>
{% endblock %}

{% block css %}
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.20/css/jquery.dataTables.min.css">
{% endblock %}

apps/tareas/templates/listar.html
{% extends "base/base.html" %}
{% block content-title %} Gestión de Tareas - {{ title }} {% endblock %}


{% block content %}

    {% if messages %}
        {% for message in messages %}
            <div class="alert alert-success alert-dismissible fade show" role="alert">
                {{ message }}
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
            </div>
        {% endfor %}
    {% endif %}

    <form class="bg-light" method="GET">
        <div class="form-row align-items-center mx-2 my-2">
            <div class="col-sm-2 text-left font-weight-bold">
                Fecha Desde
            </div>
            <div class="col-sm-3 my-1">
                <input type="date" class="form-control" type="date" name="start_date" id="start_date" value="{{ start_date }}">
            </div>
            <div class="col-sm-2 text-left font-weight-bold">
                Fecha Hasta
            </div>
            <div class="col-sm-3 my-1">
                <input type="date" class="form-control" type="date" name="end_date" id="end_date" value="{{ end_date }}">
            </div>
            
            <div class="col-sm-2 text-center">
                <button type="submit" class="btn btn-outline-primary my-1">Filtrar</button>
            </div>
        </div>
    </form>


    <table id="tproyectos" class="table table-bordered table-hover border-dark">
        <thead class="thead-dark">
            <tr>
                <th scope="col">Nombre</th>
                <th scope="col">Fecha Lím.</th>
                <th scope="col">Terminada?</th>
                <th scope="col">Prioridad</th>
                <th scope="col">Acciones</th>
            </tr>
        </thead>
        <tbody>
            {% for t in object_list %}
            <tr>
                <td>{{ t.nombre }}</td> 
                <td data-sort='YYYYMMDD'> {{ t.fecha_limite|date:'d/m/Y' }} </td>
                <td>    {% if t.terminada == True %} <span class="badge bg-success">SI</span>
                        {% else %} <span class="badge bg-danger">NO</span>
                        {% endif %}
                </td>
                <td>{{ t.prioridad.nombre }} </td>
                <td>
                    <a href="{% url 'tareas:tareas_ver' t.id %}" class="btn btn-primary btn-sm"><i class="fa-solid fa-eye"></i></a>
                    <a href="{% url 'tareas:tareas_editar' t.id %}" class="btn btn-warning btn-sm"><i class="fa-solid fa-pen-to-square"></i></a>
                    <a href="{% url 'tareas:tareas_eliminar' t.id %}" class="btn btn-danger btn-sm"><i class="fa-solid fa-trash"></i></a>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>

    <a href="{% url 'tareas:tareas_crear' %}" class="btn btn-primary">Nueva Tarea</a>

{% endblock %}

{% block js %}

    <script type="text/javascript">
        $(document).ready(function(){
        $('#start_date').change(function() {
            var fecha_desde = $(this).val();
            $('#end_date').attr({"min" : start_date});;

        });
        
        $('#end_date').change(function() {
            var end_date = $(this).val();
            $('#start_date').attr({"max" : end_date});;
        });

    });
    </script>
    <script src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js"></script>

    <script>
        $(document).ready(function() {
            $('#tproyectos').DataTable( {
                "order": [[ 2, 'asc' ], [ 1, 'desc' ]],
                "aaSorting": [],
                "pageLength" : 5,
                "lengthMenu": [[5, 10], [5, 10]],
                language: {
                        "sProcessing":     "Procesando...",
                        "sLengthMenu":     "Mostrar _MENU_ registros",
                        "sZeroRecords":    "No se encontraron resultados",
                        "sEmptyTable":     "Ningún dato disponible en esta tabla",
                        "sInfo":           "Mostrando registros del _START_ al _END_ de un total de _TOTAL_ registros",
                        "sInfoEmpty":      "Mostrando registros del 0 al 0 de un total de 0 registros",
                        "sInfoFiltered":   "(filtrado de un total de _MAX_ registros)",
                        "sInfoPostFix":    "",
                        "sSearch":         "Buscar:",
                        "sUrl":            "",
                        "sInfoThousands":  ",",
                        "sLoadingRecords": "Cargando...",

                        "oPaginate": {
                            "sFirst":    "Primero",
                            "sLast":     "Último",
                            "sNext":     "Siguiente",
                            "sPrevious": "Anterior"
                        },
                        "oAria": {
                            "sSortAscending":  ": Activar para ordenar la columna de manera ascendente",
                            "sSortDescending": ": Activar para ordenar la columna de manera descendente"
                        }

                    }
                } );
            } );
    </script>
{% endblock %}

{% block css %}
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.20/css/jquery.dataTables.min.css">
{% endblock %}

apps/tareas/templates/terminar.html
{% extends "base/base.html" %}
{% block title %} Gestión de Tareas - {{ title }} {% endblock %}
{% block body %}

<div class="card">
    <div class="card-header">
      Mini-TaskSys
    </div>
    <div class="card-body">
      <h5 class="card-title">{{ title }}</h5>
      <form method="post">
        {% csrf_token %}
        <h5>Detalle de la Tarea</h5>
        <ul class="list-group">
          <li class="list-group-item">Nombre: {{ tarea.nombre }}</li>
          <li class="list-group-item">Fecha Límite: {{ tarea.fecha_limite|date:'d/m/Y' }}</li>
          <li class="list-group-item">Prioridad: {{ tarea.prioridad.nombre }}</li>
        </ul>
        <button type="submit" class="btn btn-success mt-2">Terminar</button>
      </form>
    </div>
    </div>
    
{% endblock %}

apps/tareas/templates/ver.html
{% extends "base/base.html" %}
{% block content-title %} Gestión de Tareas - {{ title }} {% endblock %}

{% block content %}
    <form method="post">
        {% csrf_token %}
        <h2>Detalles de la Tarea</h2>
        <ul class="list-group">
          <li class="list-group-item">Nombre: {{ tarea.nombre }}</li>
          <li class="list-group-item">Fecha Límite: {{ tarea.fecha_limite|date:'d/m/Y' }}</li>
          <li class="list-group-item">Prioridad: {{ tarea.prioridad.nombre }}</li>
          <li class="list-group-item">Terminada: {% if tarea.terminada == True %} <span class="badge bg-success">SI</span>
                        {% else %} <span class="badge bg-danger">NO</span>
                        {% endif %}
          </li>
        </ul>
        <div class="text-center my-2">
            {% if tarea.terminada != True %}
                <button type="submit" class="btn btn-success">Terminar</button>
            {% endif %}
            <a href="{% url 'tareas:tareas_listar' %}" class="btn btn-secondary">Cancelar</a>
        </div>

    </form>
{% endblock %}